import { ChartBarIcon, ShieldCheckIcon, GlobeAltIcon, LightBulbIcon, HandThumbDownIcon, CogIcon} from "@heroicons/react/24/outline";

export const services = [
  {
    id: 400,
    title: "Instagram Followers | 99 Day Refill",
    rate: "NGN 2800.00",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "19 minutes",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 11169,
    title: "Instagram Followers | 99 Day Refill",
    rate: "NGN 4000.00",
    minOrder: 50,
    maxOrder: 20000,
    averageTime: "9 minutes",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 9696,
    title: "!Read Description. Instagram Followers | 99 Day Refill",
    rate: "NGN 3000.00",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "4 minutes",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 11317,
    title: "!Read Description. Instagram Followers | 99 Day Refill",
    rate: "NGN 2400.00",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "6 minutes",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 9793,
    title: "!Read Description. Instagram Followers | 99 Day Refill",
    rate: "NGN 3500.00",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "15 hours 4 minutes",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 10852,
    title: "!Read Description. Instagram Followers | 99 Day Refill",
    rate: "NGN 4000.00",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "16 minutes",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 10758,
    title: "!Read Description. Instagram Followers | 99 Day Refill",
    rate: "NGN 5000.00",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "2 hours 38 minutes",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 10958,
    title: "Threads Followers | No Refill",
    rate: "NGN 4927.26",
    minOrder: 100,
    maxOrder: 500000,
    averageTime: "116 hours 8 minutes",
    description: "Threads Followers with No Refill",
  },
  {
    id: 10901,
    title: "Threads Followers | 99 Day Refill",
    rate: "NGN 5047.40",
    minOrder: 100,
    maxOrder: 10000,
    averageTime: "189 hours 40 minutes",
    description: "Threads Followers with 99 Day Refill",
  },
  {
    id: 10902,
    title: "Thread Likes | No Refill",
    rate: "NGN 1954.45",
    minOrder: 10,
    maxOrder: 10000,
    averageTime: "8 hours 51 minutes",
    description: "Thread Likes with No Refill",
  },
  {
    id: 10870,
    title: "Thread Likes | Non Drop",
    rate: "NGN 5316.64",
    minOrder: 50,
    maxOrder: 500000,
    averageTime: "62 hours 50 minutes",
    description: "Thread Likes with Non Drop",
  },
  {
    id: 10961,
    title: "Threads Likes | 30 Day Refill",
    rate: "NGN 3176.61",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "100 hours 57 minutes",
    description: "Threads Likes with 30 Day Refill",
  },
  {
    id: 10963,
    title: "Threads Likes | High Quality",
    rate: "NGN 5316.64",
    minOrder: 50,
    maxOrder: 50000,
    averageTime: "",
    description: "Threads Likes with High Quality",
  },
  {
    id: 10851,
    title: "Thread Comments | Custom",
    rate: "NGN 8157.00",
    minOrder: 10,
    maxOrder: 10000,
    averageTime: "",
    description: "Thread Comments with Custom",
  },
  {
    id: 10850,
    title: "Thread Comments | Random",
    rate: "NGN 142517.93",
    minOrder: 5,
    maxOrder: 5000,
    averageTime: "",
    description: "Thread Comments with Random",
  },
  {
    id: 10848,
    title: "Thread Reshare | No Refill",
    rate: "NGN 10440.56",
    minOrder: 10,
    maxOrder: 5000,
    averageTime: "",
    description: "Thread Reshare with No Refill",
  },
  {
    id: 7186,
    title: "Instagram Followers | No Refill",
    rate: "NGN 6000.00",
    minOrder: 50,
    maxOrder: 20000,
    averageTime: "9 hours 10 minutes",
    description: "Instagram Followers with No Refill",
  },
  {
    id: 7001,
    title: "Instagram Followers | 99 Day Refill",
    rate: "NGN 8000.00",
    minOrder: 50,
    maxOrder: 10000,
    averageTime: "4 hours 50 minutes",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 8394,
    title: "Instagram Followers | 99 Day Refill",
    rate: "NGN 7000.00",
    minOrder: 50,
    maxOrder: 20000,
    averageTime: "9 hours",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 8396,
    title: "Instagram Followers | 99 Day Refill",
    rate: "NGN 8000.00",
    minOrder: 50,
    maxOrder: 20000,
    averageTime: "8 hours 35 minutes",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 8395,
    title: "Instagram Followers | 99 Day Refill",
    rate: "NGN 10000.00",
    minOrder: 50,
    maxOrder: 20000,
    averageTime: "7 hours 13 minutes",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 8397,
    title: "Instagram Followers | 99 Day Refill",
    rate: "NGN 12000.00",
    minOrder: 50,
    maxOrder: 20000,
    averageTime: "3 hours 56 minutes",
    description: "Instagram Followers with 99 Day Refill",
  },
  {
    id: 9947,
    title: "Instagram Likes | Works with Posts, IGTV, Reel | No Refill",
    rate: "NGN 55.64",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "11 minutes",
    description: "Instagram Likes with No Refill",
  },
  {
    id: 10197,
    title: "Instagram Likes | Works with Posts, IGTV, Reels | No Refill",
    rate: "NGN 26.46",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "11 minutes",
    description: "Instagram Likes with No Refill",
  },
  {
    id: 9902,
    title: "Instagram Likes | Works with Posts, IGTV, Reels | No Refill",
    rate: "NGN 47.60",
    minOrder: 10,
    maxOrder: 2000000,
    averageTime: "12 minutes",
    description: "Instagram Likes with No Refill",
  },
  {
    id: 9991,
    title: "Instagram Likes | Works with Posts, IGTV, Reel | No Refill",
    rate: "NGN 94.19",
    minOrder: 10,
    maxOrder: 2000000,
    averageTime: "12 minutes",
    description: "Instagram Likes with No Refill",
  },
  {
    id: 10521,
    title: "Instagram Likes | Works with Posts, IGTV, Reels | No Refill",
    rate: "NGN 109.07",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "28 minutes",
    description: "Instagram Likes with No Refill",
  },
  {
    id: 10191,
    title: "Instagram Likes | Works with Posts, IGTV, Reel | No Refill",
    rate: "NGN 349.36",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "29 minutes",
    description: "Instagram Likes with No Refill",
  },
  {
    id: 6978,
    title: "Instagram Story Views | No Refill",
    rate: "NGN 16.72",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "6 hours 24 minutes",
    description: "Instagram Story Views with No Refill",
  },
  {
    id: 9538,
    title: "Instagram Story Likes | No Refill",
    rate: "NGN 635.33",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "1 minute",
    description: "Instagram Story Likes with No Refill",
  },
  {
    id: 6979,
    title: "Instagram Story Poll Votes | No Refill",
    rate: "NGN 1070.02",
    minOrder: 100,
    maxOrder: 20000,
    averageTime: "",
    description: "Instagram Story Poll Votes with No Refill",
  },
  {
    id: 6980,
    title: "Instagram Auto Story Views | No Refill",
    rate: "NGN 33539.27",
    minOrder: 500,
    maxOrder: 200000,
    averageTime: "",
    description: "Instagram Auto Story Views with No Refill",
  },
  {
    id: 6894,
    title: "Instagram Story Poll Votes | No Refill",
    rate: "NGN 4729.76",
    minOrder: 20,
    maxOrder: 20000,
    averageTime: "",
    description: "Instagram Story Poll Votes with No Refill",
  },
  {
    id: 11297,
    title: "Instagram Auto Likes | No Refill",
    rate: "NGN 83.36",
    minOrder: 50,
    maxOrder: 20000,
    averageTime: "18 minutes",
    description: "Instagram Auto Likes with No Refill",
  },
  {
    id: 7044,
    title: "Instagram Auto Likes | No Refill",
    rate: "NGN 71.88",
    minOrder: 10,
    maxOrder: 500000,
    averageTime: "50 minutes",
    description: "Instagram Auto Likes with No Refill",
  },
  {
    id: 7046,
    title: "Instagram Auto Likes | No Refill",
    rate: "NGN 306.24",
    minOrder: 100,
    maxOrder: 60000,
    averageTime: "16 minutes",
    description: "Instagram Auto Likes with No Refill",
  },
  {
    id: 7045,
    title: "Instagram Auto Likes + Imp + Reach | No Refill",
    rate: "NGN 499.99",
    minOrder: 10,
    maxOrder: 150000,
    averageTime: "35 minutes",
    description: "Instagram Auto Likes with No Refill",
  },
  {
    id: 7073,
    title: "Instagram Auto Likes | Non Drop",
    rate: "NGN 2712.24",
    minOrder: 250,
    maxOrder: 500000,
    averageTime: "",
    description: "Instagram Auto Likes with Non Drop",
  },
  {
    id: 9805,
    title: "Instagram Likes | Nigerian Accounts",
    rate: "NGN 67508.49",
    minOrder: 100,
    maxOrder: 20000,
    averageTime: "69 hours 29 minutes",
    description: "Instagram Likes with Nigerian Accounts",
  },
  {
    id: 8128,
    title: "Instagram Comments | Random - Positive",
    rate: "NGN 15253.89",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "43 minutes",
    description: "Instagram Comments with Random - Positive",
  },
  {
    id: 9871,
    title: "Instagram Comments | Random - Negative",
    rate: "NGN 15178.75",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "55 minutes",
    description: "Instagram Comments with Random - Negative",
  },
  {
    id: 8199,
    title: "Instagram Comments | Emoji - Positive",
    rate: "NGN 14903.89",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "14 minutes",
    description: "Instagram Comments with Emoji - Positive",
  },
  {
    id: 6983,
    title: "Instagram Comments | Emoji - Negative",
    rate: "NGN 14872.87",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "4 hours 46 minutes",
    description: "Instagram Comments with Emoji - Negative",
  },
  {
    id: 10140,
    title: "Instagram Comments | Custom Comments",
    rate: "NGN 36248.66",
    minOrder: 10,
    maxOrder: 20000,
    averageTime: "53 minutes",
    description: "Instagram Comments with Custom Comments",
  },
  {
    id: 10976,
    title: "Instagram Comments | Random - Positive",
    rate: "NGN 6752.00",
    minOrder: 10,
    maxOrder: 100000,
    averageTime: "7 hours 27 minutes",
    description: "Instagram Comments with Random - Positive",
  },
  {
    id: 10978,
    title: "Instagram Comments | Random - Negative",
    rate: "NGN 6752.00",
    minOrder: 10,
    maxOrder: 100000,
    averageTime: "45 hours 10 minutes",
    description: "Instagram Comments with Random - Negative",
  },
  {
    id: 10977,
    title: "Instagram Comments | Random - English Accounts",
    rate: "NGN 6752.00",
    minOrder: 10,
    maxOrder: 100000,
    averageTime: "46 hours 6 minutes",
    description: "Instagram Comments with Random - English Accounts",
  },
  {
    id: 10938,
    title: "Instagram Comments | Custom",
    rate: "NGN 6752.00",
    minOrder: 10,
    maxOrder: 10000,
    averageTime: "33 hours 7 minutes",
    description: "Instagram Comments with Custom",
  },
  {
    id: 10939,
    title: "Instagram Comments | Custom",
    rate: "NGN 6752.00",
    minOrder: 10,
    maxOrder: 5000,
    averageTime: "37 hours 24 minutes",
    description: "Instagram Comments with Custom",
  },
];

const homeServices = [
  {
    title: "Content Scheduling",
    category: "Social Media Management",
    description: "Schedule your content to be posted at optimal times.",
    icon: ChartBarIcon,
  },
  {
    title: "Post Automation",
    category: "Social Media Management",
    description: "Automate your posts to save time and increase efficiency.",
    icon: ShieldCheckIcon,
  },
  {
    title: "Engagement Tracking",
    category: "Social Media Management",
    description: "Track engagement metrics to understand your audience better.",
    icon: CogIcon,
  },
  {
    title: "Analytics and Reporting",
    category: "Social Media Management",
    description:
      "Get detailed analytics and reports on your social media performance.",
    icon: HandThumbDownIcon,
  },
  {
    title: "Graphic Design",
    category: "Content Creation",
    description: "Create visually appealing graphics for your content.",
    icon: ChartBarIcon,
  },
  {
    title: "Engagement Tracking",
    category: "Social Media Management",
    description: "Track engagement metrics to understand your audience better.",
    icon: CogIcon,
  },
];

export { homeServices };
